import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store,MemoryStore } from '../server/store.mjs';
import { Walkthrough,initialData,exampleListing } from '../server/domain.mjs';
import { Payments } from '../server/payments.mjs';
const renter={role:'renter',id:'renter-demo'},verifier={role:'verifier',id:'verifier-demo'},operator={role:'operator',id:'operator-demo'};
function setup(){const store=new MemoryStore(initialData),pay=new Payments(store,{PAYMENT_MODE:'simulated'}),app=new Walkthrough(store,pay,{});return {store,app,c:store.data.cases[0]};}
async function schedule(app,c,slotId='maya-am'){await app.action(c.id,'scope',{accepted:true,access:true,contact:'Demo contact',slotId},renter);await app.action(c.id,'order',{},renter);await app.action(c.id,'authorize',{},renter);}
function evidence(c,itemId,n=1){return {itemId,sessionId:c.session.id,challenge:c.session.phrase,observation:itemId==='kitchen'?'inconsistent':'matched',note:itemId==='kitchen'?'Dishwasher was absent in the staged scene.':'Observed the requested feature in the staged scene.',synthetic:true,data:'data:image/png;base64,'+Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),Buffer.from(`${c.id}-${itemId}-${n}`)]).toString('base64')};}
async function reviewed(app,c,opts={}){await schedule(app,c);await app.action(c.id,'start',{},verifier);for(const i of c.scope)await app.action(c.id,'evidence',evidence(c,i.id),verifier);await app.action(c.id,'submit',{},verifier);await app.action(c.id,'review',{confirmed:true,note:'Independently checked all agreed items and image links.',...opts},operator);}
test('adverse complete report captures fixed fee and preserves independent earning',async()=>{const {app,c,store}=setup();await reviewed(app,c);assert.equal(c.state,'complete');assert.equal(c.payment.status,'captured');assert.equal(c.assessment.find(x=>x.itemId==='kitchen').status,'inconsistent');assert.equal(c.earning.amountMinor,4000);assert.equal(c.earning.status,'pending');assert.equal(c.earning.payoutStatus,'not_submitted');await assert.rejects(app.action(c.id,'review',{confirmed:true},operator));assert.equal(store.data.operations.filter(o=>o.type==='capture').length,1);});
test('incomplete access voids authorization and releases slot',async()=>{const {app,c,store}=setup();await schedule(app,c);await app.action(c.id,'incomplete',{reason:'Access denied at the door.'},verifier);assert.equal(c.payment.status,'voided');assert.equal(c.state,'incomplete');assert.equal(store.data.slots[0].caseId,null);assert.equal(c.earning.payoutStatus,'not_submitted');});
test('verifier cannot approve completion; uncovered item cannot capture',async()=>{const {app,c}=setup();await schedule(app,c);await app.action(c.id,'start',{},verifier);await app.action(c.id,'evidence',evidence(c,c.scope[0].id),verifier);await app.action(c.id,'submit',{},verifier);await assert.rejects(app.action(c.id,'review',{confirmed:true},verifier),/correct independent role/);await assert.rejects(app.action(c.id,'review',{confirmed:true,note:'Reviewed available material.'},operator),/Missing evidence/);assert.equal(c.payment.status,'authorized');});
test('stale challenge and reused file rejected',async()=>{const {app,c}=setup();await schedule(app,c);await app.action(c.id,'start',{},verifier);const e=evidence(c,c.scope[0].id);await assert.rejects(app.action(c.id,'evidence',{...e,challenge:'OLD'},verifier),/current visit/);await app.action(c.id,'evidence',e,verifier);await assert.rejects(app.action(c.id,'evidence',{...e,itemId:c.scope[1].id},verifier),/already been submitted/);});
test('concurrent appointments cannot double book',async()=>{const {app,c,store}=setup();const d=await app.action(null,'create',{title:'Second case',listing:exampleListing,consent:true},renter);for(const x of [c,d]){await app.action(x.id,'scope',{accepted:true,access:true,contact:'Demo contact',slotId:'maya-am'},renter);await app.action(x.id,'order',{},renter);}const results=await Promise.allSettled([app.action(c.id,'authorize',{},renter),app.action(d.id,'authorize',{},renter)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(store.data.operations.filter(o=>o.type==='authorize').length,1);assert.equal(store.data.slots[0].caseId,c.id);});
test('lost capture response remains unknown until read reconciliation; no duplicate capture',async()=>{const {app,c,store}=setup();await reviewed(app,c,{simulateTimeout:true});assert.equal(c.state,'complete');assert.equal(c.payment.status,'unknown');assert.equal(c.earning.fundingRequired,true);await app.action(c.id,'reconcile',{},operator);assert.equal(c.payment.status,'captured');assert.equal(c.earning.fundingRequired,false);assert.equal(store.data.operations.filter(o=>o.type==='capture').length,1);});
test('late authorization reconciles to void if another case took the slot',async()=>{const {app,c}=setup();await app.action(c.id,'scope',{accepted:true,access:true,contact:'Demo contact',slotId:'maya-am'},renter);await app.action(c.id,'order',{},renter);await assert.rejects(app.action(c.id,'authorize',{simulateTimeout:true},renter));const d=await app.action(null,'create',{listing:exampleListing,consent:true},renter);await schedule(app,d);await app.action(c.id,'reconcile',{},operator);assert.equal(c.state,'incomplete');assert.equal(c.payment.status,'voided');assert.equal(d.state,'scheduled');});
test('appeal freezes earning and operator refund is separately confirmed',async()=>{const {app,c}=setup();await reviewed(app,c);await app.action(c.id,'appeal',{reason:'The bedroom window was not adequately documented.'},renter);assert.equal(c.earning.status,'held');await assert.rejects(app.action(c.id,'eligibility',{},operator));await app.action(c.id,'resolve',{decision:'refund',note:'Service coverage did not meet the accepted scope.'},operator);assert.equal(c.payment.status,'refunded');assert.equal(c.earning.payoutStatus,'not_submitted');});
test('payout eligibility requires window; demo clock never marks paid',async()=>{const {app,c}=setup();await reviewed(app,c);await assert.rejects(app.action(c.id,'eligibility',{},operator),/48-hour/);await app.action(c.id,'advance-demo',{},operator);await app.action(c.id,'eligibility',{},operator);assert.equal(c.earning.status,'eligible');assert.equal(c.earning.payoutStatus,'not_submitted');});
test('bad scope input leaves no partial approval mutation',async()=>{const {app,c}=setup();await assert.rejects(app.action(c.id,'scope',{accepted:true,access:true,slotId:'maya-am',contact:''},renter));assert.equal(c.scopeAccepted,false);assert.equal(c.access,false);});
test('frozen scope and expired service cannot be bypassed',async()=>{const {app,c}=setup();await schedule(app,c);await assert.rejects(app.action(c.id,'checklist',{},renter),/frozen/);c.payment.expiresAt='2020-01-01T00:00:00Z';await assert.rejects(app.action(c.id,'start',{},verifier),/expired/);await app.action(c.id,'expire',{reason:'48-hour service window expired.'},operator);assert.equal(c.payment.status,'voided');});
test('state survives restart and mode mixing is rejected',()=>{const dir=mkdtempSync(join(tmpdir(),'walkthrough-test-'));try{let store=new Store(dir,initialData);store.data.cases[0].questions='Saved question';store.save();store=new Store(dir,initialData);assert.equal(store.data.cases[0].questions,'Saved question');assert.throws(()=>new Payments(store,{PAYMENT_MODE:'sandbox'}),/differs/);assert.throws(()=>new Payments(store,{PAYMENT_MODE:'sandbx'}),/must be/);}finally{rmSync(dir,{recursive:true,force:true});}});
