import test from 'node:test';
import sharp from 'sharp';
import { checklist, ruleChecklist } from '../server/ai.mjs';
import { printableReport } from '../server/report.mjs';
const images=await Promise.all(Array.from({length:240},(_,i)=>sharp({create:{width:24,height:24,channels:3,background:{r:i,g:100,b:70}}}).png().toBuffer()));
let imageIndex=0;
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store,MemoryStore } from '../server/store.mjs';
import { Walkthrough,initialData,exampleListing } from '../server/domain.mjs';
import { Payments } from '../server/payments.mjs';
const renter={role:'renter',id:'renter-demo'},verifier={role:'verifier',id:'verifier-demo'},operator={role:'operator',id:'operator-demo'};
function setup(){const store=new MemoryStore(initialData),pay=new Payments(store,{PAYMENT_MODE:'simulated'}),app=new Walkthrough(store,pay,{});return {store,app,c:store.data.cases[0]};}
async function schedule(app,c,slotId='maya-am'){await app.action(c.id,'scope',{accepted:true,access:true,contact:'Demo contact',slotId},renter);await app.action(c.id,'order',{},renter);await app.action(c.id,'authorize',{},renter);}
function evidence(c,itemId,n=1){return {itemId,sessionId:c.session.id,challenge:c.session.phrase,observation:itemId==='kitchen'?'inconsistent':'matched',note:itemId==='kitchen'?'Dishwasher was absent in the staged scene.':'Observed the requested feature in the staged scene.',synthetic:true,data:'data:image/png;base64,'+images[imageIndex++%images.length].toString('base64')};}
async function reviewed(app,c,opts={}){await schedule(app,c);await app.action(c.id,'start',{},verifier);for(const i of c.scope)await app.action(c.id,'evidence',evidence(c,i.id),verifier);await app.action(c.id,'submit',{},verifier);await app.action(c.id,'review',{confirmed:true,note:'Independently checked all agreed items and image links.',...opts},operator);}
test('adverse complete report captures fixed fee and preserves independent earning',async()=>{const {app,c,store}=setup();await reviewed(app,c);assert.equal(c.state,'complete');assert.equal(c.payment.status,'captured');assert.equal(c.assessment.find(x=>x.itemId==='kitchen').status,'inconsistent');assert.equal(c.earning.amountMinor,4000);assert.equal(c.earning.status,'pending');assert.equal(c.earning.payoutStatus,'not_submitted');await assert.rejects(app.action(c.id,'review',{confirmed:true},operator));assert.equal(store.data.operations.filter(o=>o.type==='capture').length,1);});
test('incomplete access voids authorization and releases slot',async()=>{const {app,c,store}=setup();await schedule(app,c);await app.action(c.id,'incomplete',{reason:'Access denied at the door.'},verifier);assert.equal(c.payment.status,'voided');assert.equal(c.state,'incomplete');assert.equal(store.data.slots[0].caseId,null);assert.equal(c.earning.payoutStatus,'not_submitted');});
test('verifier cannot approve completion; uncovered item cannot capture',async()=>{const {app,c}=setup();await schedule(app,c);await app.action(c.id,'start',{},verifier);await app.action(c.id,'evidence',evidence(c,c.scope[0].id),verifier);await app.action(c.id,'submit',{},verifier);await assert.rejects(app.action(c.id,'review',{confirmed:true},verifier),/correct independent role/);await assert.rejects(app.action(c.id,'review',{confirmed:true,note:'Reviewed available material.'},operator),/Missing evidence/);assert.equal(c.payment.status,'authorized');});
test('stale challenge and reused file rejected',async()=>{const {app,c}=setup();await schedule(app,c);await app.action(c.id,'start',{},verifier);const e=evidence(c,c.scope[0].id);await assert.rejects(app.action(c.id,'evidence',{...e,challenge:'OLD'},verifier),/current visit/);await app.action(c.id,'evidence',e,verifier);await assert.rejects(app.action(c.id,'evidence',{...e,itemId:c.scope[1].id},verifier),/already been submitted/);});
test('concurrent appointments cannot double book',async()=>{const {app,c,store}=setup();const d=await app.action(null,'create',{title:'Second case',listing:exampleListing,consent:true},renter);for(const x of [c,d]){await app.action(x.id,'scope',{accepted:true,access:true,contact:'Demo contact',slotId:'maya-am'},renter);await app.action(x.id,'order',{},renter);}const results=await Promise.allSettled([app.action(c.id,'authorize',{},renter),app.action(d.id,'authorize',{},renter)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(store.data.operations.filter(o=>o.type==='authorize').length,1);assert.equal(store.data.slots[0].caseId,c.id);});
test('lost capture response remains unknown until read reconciliation; no duplicate capture',async()=>{const {app,c,store}=setup();await reviewed(app,c,{simulateTimeout:true});assert.equal(c.state,'complete');assert.equal(c.payment.status,'unknown');assert.equal(c.earning.fundingRequired,true);await app.action(c.id,'reconcile',{},operator);assert.equal(c.payment.status,'captured');assert.equal(c.earning.fundingRequired,false);assert.equal(store.data.operations.filter(o=>o.type==='capture').length,1);});
test('late authorization reconciles to void if another case took the slot',async()=>{const {app,c}=setup();await app.action(c.id,'scope',{accepted:true,access:true,contact:'Demo contact',slotId:'maya-am'},renter);await app.action(c.id,'order',{},renter);await assert.rejects(app.action(c.id,'authorize',{simulateTimeout:true},renter));const d=await app.action(null,'create',{listing:exampleListing,consent:true},renter);await schedule(app,d);await app.action(c.id,'reconcile',{},operator);assert.equal(c.state,'incomplete');assert.equal(c.payment.status,'voided');assert.equal(d.state,'scheduled');});
test('appeal freezes earning and operator refund is separately confirmed',async()=>{const {app,c}=setup();await reviewed(app,c);await app.action(c.id,'appeal',{reason:'The bedroom window was not adequately documented.'},renter);assert.equal(c.earning.status,'held');await assert.rejects(app.action(c.id,'eligibility',{},operator));await app.action(c.id,'resolve',{decision:'refund',note:'Service coverage did not meet the accepted scope.'},operator);assert.equal(c.payment.status,'refunded');assert.equal(c.earning.payoutStatus,'not_submitted');});
test('payout eligibility requires window; demo clock never marks paid',async()=>{const {app,c}=setup();await reviewed(app,c);await assert.rejects(app.action(c.id,'eligibility',{},operator),/48-hour/);await app.action(c.id,'advance-demo',{},operator);await app.action(c.id,'eligibility',{},operator);assert.equal(c.earning.status,'eligible');assert.equal(c.earning.payoutStatus,'not_submitted');});
test('bad scope input leaves no partial approval mutation',async()=>{const {app,c}=setup();await assert.rejects(app.action(c.id,'scope',{accepted:true,access:true,slotId:'maya-am',contact:''},renter));assert.equal(c.scopeAccepted,false);assert.equal(c.access,false);});
test('frozen scope and expired service cannot be bypassed',async()=>{const {app,c}=setup();await schedule(app,c);await assert.rejects(app.action(c.id,'checklist',{},renter),/frozen/);c.payment.expiresAt='2020-01-01T00:00:00Z';await assert.rejects(app.action(c.id,'start',{},verifier),/expired/);await app.action(c.id,'expire',{reason:'48-hour service window expired.'},operator);assert.equal(c.payment.status,'voided');});
test('state survives restart and mode mixing is rejected',()=>{const dir=mkdtempSync(join(tmpdir(),'walkthrough-test-'));try{let store=new Store(dir,initialData);store.data.cases[0].questions='Saved question';store.save();store=new Store(dir,initialData);assert.equal(store.data.cases[0].questions,'Saved question');assert.throws(()=>new Payments(store,{PAYMENT_MODE:'sandbox'}),/differs/);assert.throws(()=>new Payments(store,{PAYMENT_MODE:'sandbx'}),/must be/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('verified webhook reconciles unknown payment AND applies domain state; duplicate event is harmless',async()=>{const {app,c,store}=setup();await reviewed(app,c,{simulateTimeout:true});const event={id:'WH-CAPTURE-DEMO',resource:{supplementary_data:{related_ids:{order_id:c.payment.orderId}}}};await app.webhook(event);assert.equal(c.payment.status,'captured');assert.equal(c.state,'complete');assert.equal(c.earning.fundingRequired,false);assert.equal(store.data.operations.find(o=>o.type==='capture').status,'confirmed');await app.webhook(event);assert.equal(store.data.webhookIds.length,1);assert.equal(store.data.operations.filter(o=>o.type==='capture').length,1);});
test('slot conflict can recover by changing appointment without unfreezing scope',async()=>{const {app,c}=setup();const d=await app.action(null,'create',{listing:exampleListing,consent:true},renter);for(const x of [c,d])await app.action(x.id,'scope',{accepted:true,access:true,contact:'Demo contact',slotId:'maya-am'},renter);const scope=JSON.stringify(d.scope);await app.action(c.id,'order',{},renter);await app.action(c.id,'authorize',{},renter);await app.action(d.id,'order',{},renter);await assert.rejects(app.action(d.id,'authorize',{},renter));await app.action(d.id,'reschedule',{slotId:'maya-pm',access:true},renter);await app.action(d.id,'authorize',{},renter);assert.equal(d.state,'scheduled');assert.equal(d.slotId,'maya-pm');assert.equal(JSON.stringify(d.scope),scope);assert.equal(d.scopeAccepted,true);});
test('expiry worker closes overdue service and confirms void',async()=>{const {app,c,store}=setup();await schedule(app,c);c.payment.expiresAt='2020-01-01T00:00:00Z';await app.expireDue();assert.equal(c.state,'incomplete');assert.equal(c.payment.status,'voided');assert.equal(store.data.slots[0].caseId,null);});
test('reset requires operator and only clears simulated demo',async()=>{const {app,c,store}=setup();await reviewed(app,c);await assert.rejects(app.reset(renter),/role/);await app.reset(operator);assert.equal(store.data.cases.length,1);assert.equal(store.data.operations.length,0);assert.equal(store.data.cases[0].state,'awaiting_access');app.payments.mode='sandbox';await assert.rejects(app.reset(operator),/simulated/);});
test('review cannot capture after service deadline even before the expiry worker runs',async()=>{const {app,c,store}=setup();await schedule(app,c);await app.action(c.id,'start',{},verifier);for(const item of c.scope)await app.action(c.id,'evidence',evidence(c,item.id),verifier);await app.action(c.id,'submit',{},verifier);c.payment.expiresAt='2020-01-01T00:00:00Z';await assert.rejects(app.action(c.id,'review',{confirmed:true,note:'All deliverables independently checked.'},operator),/expired/);assert.equal(c.state,'evidence_review');assert.equal(store.data.operations.filter(o=>o.type==='capture').length,0);});

for(const type of ['capture','void','refund'])test(`restart replays confirmed ${type} checkpoint without dispatch or duplicate effects`,async()=>{
 const {app,c,store}=setup();const checkpoints=[];store.save=()=>checkpoints.push(structuredClone(store.data));
 if(type==='void'){await schedule(app,c);await app.action(c.id,'incomplete',{reason:'Access not available for this visit.'},verifier);}else{await reviewed(app,c);if(type==='refund'){await app.action(c.id,'appeal',{reason:'A scoped item was not adequately documented.'},renter);await app.action(c.id,'resolve',{decision:'refund',note:'Independent review approved a service refund.'},operator);}}
 const checkpoint=checkpoints.find(d=>d.operations.some(o=>o.type===type&&o.status==='confirmed'&&!o.appliedAt));assert.ok(checkpoint);
 const replayStore=new MemoryStore(()=>checkpoint),payments=new Payments(replayStore,{PAYMENT_MODE:'simulated'}),restarted=new Walkthrough(replayStore,payments,{});payments.operation=()=>{throw Error('Recovery must not dispatch another financial operation');};
 await restarted.recoverConfirmed();const recovered=replayStore.data.cases[0];assert.equal(recovered.payment.status,{capture:'captured',void:'voided',refund:'refunded'}[type]);assert.ok(replayStore.data.operations.find(o=>o.type===type).appliedAt);if(type==='refund'){assert.equal(recovered.appeal.status,'refund');assert.equal(recovered.state,'complete');assert.equal(recovered.earning.status,'held');}
 const applied=replayStore.data.operations.find(o=>o.type===type).appliedAt;await restarted.recoverConfirmed();await restarted.action(recovered.id,'reconcile',{},operator);assert.equal(replayStore.data.operations.find(o=>o.type===type).appliedAt,applied);assert.equal(replayStore.data.operations.filter(o=>o.type===type).length,1);
});
test('question coverage survives editing, exclusions, and frozen scope consent',async()=>{const {app}=setup();const c=await app.action(null,'create',{listing:'Shared basement laundry in a Cambridge apartment with windows.',questions:'Photograph basement water stains. Check whether the washing machine is present. Can you verify legal authority?',consent:true},renter);assert.equal(c.scope.filter(i=>i.questionId).length,3);assert.equal(c.scope.at(-1).excluded,true);await assert.rejects(app.action(c.id,'edit-scope',{items:c.scope.filter(i=>!i.questionId)},renter),/Every renter question/);const items=c.scope.map(i=>({...i,request:i.questionId==='q-1'?'Photograph all visible basement water stains from a safe accessible position.':i.request}));await app.action(c.id,'edit-scope',{items},renter);await schedule(app,c);assert.equal(c.acceptedScopeVersion,2);assert.deepEqual(c.frozenScope,c.scope);await assert.rejects(app.action(c.id,'edit-scope',{items},renter),/frozen/);});
test('task-specific correction reaches verifier and persists after resubmission',async()=>{const {app,c,store}=setup();await schedule(app,c);await app.action(c.id,'start',{},verifier);await app.action(c.id,'evidence',evidence(c,c.scope[0].id),verifier);await app.action(c.id,'submit',{},verifier);await assert.rejects(app.action(c.id,'return',{note:'Redo the photo clearly.'},operator),/Select/);await app.action(c.id,'return',{note:'Retake entrance number with the session phrase visible.',itemIds:[c.scope[0].id]},operator);assert.equal(app.snapshot(verifier).cases[0].corrections[0].itemIds[0],c.scope[0].id);assert.match(c.corrections[0].note,/session phrase/);const reopened=new MemoryStore(()=>structuredClone(store.data));assert.equal(reopened.data.cases[0].corrections.length,1);});
test('decoder rejects signature-only, truncated, oversized-pixel and tiny images; real JPEG/WebP accepted',async()=>{const {app,c}=setup();await schedule(app,c);await app.action(c.id,'start',{},verifier);const e=evidence(c,c.scope[0].id);const invalid=[Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),Buffer.from('not pixels')]),images[0].subarray(0,45),await sharp({create:{width:1,height:1,channels:3,background:'red'}}).png().toBuffer(),await sharp({create:{width:5000,height:5000,channels:3,background:'white'}}).png().toBuffer()];for(const bytes of invalid)await assert.rejects(app.action(c.id,'evidence',{...e,data:'data:image/png;base64,'+bytes.toString('base64')},verifier),/decoded safely/);for(const format of ['jpeg','webp']){const bytes=await sharp(images[format==='jpeg'?1:2])[format]().toBuffer();await app.action(c.id,'evidence',{...e,data:`data:image/${format};base64,`+bytes.toString('base64')},verifier);}assert.equal(c.evidence.length,2);assert.ok(c.evidence.every(e=>e.data.startsWith('data:image/png;base64,')));});
test('model validator rejects empty and duplicated claims or requests',async()=>{const original=globalThis.fetch;try{for(const items of [Array.from({length:3},()=>({claim:'',title:'Kitchen condition',request:'Photograph the visible kitchen surfaces.'})),Array.from({length:3},()=>({claim:'Sunny one-bedroom apartment in Cambridge',title:'Kitchen condition',request:'Photograph the visible kitchen surfaces.'}))]){globalThis.fetch=async()=>({ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({items})}]}]})});await assert.rejects(checklist(exampleListing,'',{AI_MODE:'openai',OPENAI_API_KEY:'test-only'}),/grounded/);}}finally{globalThis.fetch=original;}});
test('printable report embeds evidence, adverse finding, question and privacy boundary',async()=>{const {app,c}=setup();await reviewed(app,c);const html=printableReport(c);assert.match(html,/data:image\/png;base64/);assert.match(html,/Dishwasher was absent/);assert.match(html,/How much natural light/);assert.match(html,/SYNTHETIC STAGED ILLUSTRATION/);assert.match(html,/not_submitted/);assert.match(html,/does not establish ownership/);});
