import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { checklist, ruleChecklist } from '../server/ai.mjs';
const live=process.argv.includes('--live');
if(live&&!process.env.OPENAI_API_KEY)throw new Error('Set OPENAI_API_KEY locally for the explicit live evaluation. Offline evaluation never contacts a provider.');
const source=readFileSync(new URL('../eval/listings.json',import.meta.url),'utf8');
const examples=JSON.parse(source),results=[];
function metrics(items,example){const body=items.map(i=>`${i.claim} ${i.request}`).join(' ').toLowerCase();return {concerns:example.concerns.length,represented:example.concerns.filter(term=>body.includes(term.toLowerCase())).length,unsupportedListingQuotes:items.filter(i=>i.source==='listing text'&&!example.listing.includes(i.claim)).length,excludedItems:items.filter(i=>i.excluded).length,itemCount:items.length};}
for(const example of examples){const start=performance.now();const baseline=ruleChecklist(example.listing);const result=await checklist(example.listing,example.questions,live?{...process.env,AI_MODE:'openai'}:{AI_MODE:'rules'});results.push({id:example.id,baseline:metrics(baseline,example),candidate:metrics(result.items,example),latencyMs:Number((performance.now()-start).toFixed(3)),tokens:result.meta.tokens,costUsd:result.meta.costUsd,items:result.items,humanRelevance:null,humanEditingSeconds:null});}
const total=key=>results.reduce((n,r)=>n+r.candidate[key],0);const report={version:1,datasetSha256:createHash('sha256').update(source).digest('hex'),executedAt:new Date().toISOString(),mode:live?'live-openai':'offline-rules',model:live?process.env.OPENAI_MODEL||'gpt-4o-mini':null,providerRequests:live?examples.length:0,method:'Exact concern-term presence in scope reference/request. This measures mechanical retention, not semantic usefulness, photograph quality, or model superiority. Human relevance/edit-time fields remain unmeasured.',summary:{examples:results.length,concerns:total('concerns'),baselineRepresented:results.reduce((n,r)=>n+r.baseline.represented,0),candidateRepresented:total('represented'),unsupportedListingQuotes:total('unsupportedListingQuotes'),meanLatencyMs:Number((results.reduce((n,r)=>n+r.latencyMs,0)/results.length).toFixed(3))},results};
const path=new URL(`../eval/results-${live?'live':'local'}.json`,import.meta.url);writeFileSync(path,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({file:path.pathname,...report.summary,mode:report.mode,providerRequests:report.providerRequests},null,2));
